// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * EventType represents a type of event that can be consumed from a resource.
 */
export class EventType extends pulumi.CustomResource {
    /**
     * Get an existing EventType resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): EventType {
        return new EventType(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:eventing.knative.dev/v1beta1:EventType';

    /**
     * Returns true if the given object is an instance of EventType.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EventType {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EventType.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"eventing.knative.dev/v1beta1" | undefined>;
    public readonly kind!: pulumi.Output<"EventType" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * Spec defines the desired state of the EventType.
     */
    public readonly spec!: pulumi.Output<outputs.eventing.v1beta1.EventTypeSpec | undefined>;
    /**
     * Status represents the current state of the EventType. This data may be out of date.
     */
    public readonly status!: pulumi.Output<outputs.eventing.v1beta1.EventTypeStatus | undefined>;

    /**
     * Create a EventType resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: EventTypeArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "eventing.knative.dev/v1beta1";
            resourceInputs["kind"] = "EventType";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EventType.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a EventType resource.
 */
export interface EventTypeArgs {
    apiVersion?: pulumi.Input<"eventing.knative.dev/v1beta1">;
    kind?: pulumi.Input<"EventType">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Spec defines the desired state of the EventType.
     */
    spec?: pulumi.Input<inputs.eventing.v1beta1.EventTypeSpecArgs>;
    /**
     * Status represents the current state of the EventType. This data may be out of date.
     */
    status?: pulumi.Input<inputs.eventing.v1beta1.EventTypeStatusArgs>;
}
