// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { EventTypeArgs } from "./eventType";
export type EventType = import("./eventType").EventType;
export const EventType: typeof import("./eventType").EventType = null as any;
utilities.lazyLoad(exports, ["EventType"], () => require("./eventType"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:eventing.knative.dev/v1beta1:EventType":
                return new EventType(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("knative-pulumi", "eventing.knative.dev/v1beta1", _module)
