// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { EventTypeArgs } from "./eventType";
export type EventType = import("./eventType").EventType;
export const EventType: typeof import("./eventType").EventType = null as any;
utilities.lazyLoad(exports, ["EventType"], () => require("./eventType"));

export { EventTypeListArgs } from "./eventTypeList";
export type EventTypeList = import("./eventTypeList").EventTypeList;
export const EventTypeList: typeof import("./eventTypeList").EventTypeList = null as any;
utilities.lazyLoad(exports, ["EventTypeList"], () => require("./eventTypeList"));

export { EventTypePatchArgs } from "./eventTypePatch";
export type EventTypePatch = import("./eventTypePatch").EventTypePatch;
export const EventTypePatch: typeof import("./eventTypePatch").EventTypePatch = null as any;
utilities.lazyLoad(exports, ["EventTypePatch"], () => require("./eventTypePatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:eventing.knative.dev/v1beta1:EventType":
                return new EventType(name, <any>undefined, { urn })
            case "kubernetes:eventing.knative.dev/v1beta1:EventTypeList":
                return new EventTypeList(name, <any>undefined, { urn })
            case "kubernetes:eventing.knative.dev/v1beta1:EventTypePatch":
                return new EventTypePatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("knative-pulumi", "eventing.knative.dev/v1beta1", _module)
