// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

export class EventTransform extends pulumi.CustomResource {
    /**
     * Get an existing EventTransform resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): EventTransform {
        return new EventTransform(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:eventing.knative.dev/v1alpha1:EventTransform';

    /**
     * Returns true if the given object is an instance of EventTransform.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EventTransform {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EventTransform.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"eventing.knative.dev/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"EventTransform" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * Spec defines the desired state of the EventTransform.
     */
    public readonly spec!: pulumi.Output<outputs.eventing.v1alpha1.EventTransformSpec | undefined>;
    /**
     * Status represents the current state of the EventTransform. This data may be out of date.
     */
    public readonly status!: pulumi.Output<outputs.eventing.v1alpha1.EventTransformStatus | undefined>;

    /**
     * Create a EventTransform resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: EventTransformArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "eventing.knative.dev/v1alpha1";
            resourceInputs["kind"] = "EventTransform";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EventTransform.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a EventTransform resource.
 */
export interface EventTransformArgs {
    apiVersion?: pulumi.Input<"eventing.knative.dev/v1alpha1">;
    kind?: pulumi.Input<"EventTransform">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Spec defines the desired state of the EventTransform.
     */
    spec?: pulumi.Input<inputs.eventing.v1alpha1.EventTransformSpecArgs>;
    /**
     * Status represents the current state of the EventTransform. This data may be out of date.
     */
    status?: pulumi.Input<inputs.eventing.v1alpha1.EventTransformStatusArgs>;
}
