// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { EventPolicyArgs } from "./eventPolicy";
export type EventPolicy = import("./eventPolicy").EventPolicy;
export const EventPolicy: typeof import("./eventPolicy").EventPolicy = null as any;
utilities.lazyLoad(exports, ["EventPolicy"], () => require("./eventPolicy"));

export { EventTransformArgs } from "./eventTransform";
export type EventTransform = import("./eventTransform").EventTransform;
export const EventTransform: typeof import("./eventTransform").EventTransform = null as any;
utilities.lazyLoad(exports, ["EventTransform"], () => require("./eventTransform"));

export { RequestReplyArgs } from "./requestReply";
export type RequestReply = import("./requestReply").RequestReply;
export const RequestReply: typeof import("./requestReply").RequestReply = null as any;
utilities.lazyLoad(exports, ["RequestReply"], () => require("./requestReply"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:eventing.knative.dev/v1alpha1:EventPolicy":
                return new EventPolicy(name, <any>undefined, { urn })
            case "kubernetes:eventing.knative.dev/v1alpha1:EventTransform":
                return new EventTransform(name, <any>undefined, { urn })
            case "kubernetes:eventing.knative.dev/v1alpha1:RequestReply":
                return new RequestReply(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("knative-pulumi", "eventing.knative.dev/v1alpha1", _module)
