// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { ApiServerSourceArgs } from "./apiServerSource";
export type ApiServerSource = import("./apiServerSource").ApiServerSource;
export const ApiServerSource: typeof import("./apiServerSource").ApiServerSource = null as any;
utilities.lazyLoad(exports, ["ApiServerSource"], () => require("./apiServerSource"));

export { ContainerSourceArgs } from "./containerSource";
export type ContainerSource = import("./containerSource").ContainerSource;
export const ContainerSource: typeof import("./containerSource").ContainerSource = null as any;
utilities.lazyLoad(exports, ["ContainerSource"], () => require("./containerSource"));

export { PingSourceArgs } from "./pingSource";
export type PingSource = import("./pingSource").PingSource;
export const PingSource: typeof import("./pingSource").PingSource = null as any;
utilities.lazyLoad(exports, ["PingSource"], () => require("./pingSource"));

export { SinkBindingArgs } from "./sinkBinding";
export type SinkBinding = import("./sinkBinding").SinkBinding;
export const SinkBinding: typeof import("./sinkBinding").SinkBinding = null as any;
utilities.lazyLoad(exports, ["SinkBinding"], () => require("./sinkBinding"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:sources.knative.dev/v1:ApiServerSource":
                return new ApiServerSource(name, <any>undefined, { urn })
            case "kubernetes:sources.knative.dev/v1:ContainerSource":
                return new ContainerSource(name, <any>undefined, { urn })
            case "kubernetes:sources.knative.dev/v1:PingSource":
                return new PingSource(name, <any>undefined, { urn })
            case "kubernetes:sources.knative.dev/v1:SinkBinding":
                return new SinkBinding(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("knative-pulumi", "sources.knative.dev/v1", _module)
