// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * PingSource describes an event source with a fixed payload produced on a specified cron schedule.
 */
export class PingSource extends pulumi.CustomResource {
    /**
     * Get an existing PingSource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PingSource {
        return new PingSource(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:sources.knative.dev/v1:PingSource';

    /**
     * Returns true if the given object is an instance of PingSource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PingSource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PingSource.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"sources.knative.dev/v1" | undefined>;
    public readonly kind!: pulumi.Output<"PingSource" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * PingSourceSpec defines the desired state of the PingSource (from the client).
     */
    public readonly spec!: pulumi.Output<outputs.sources.v1.PingSourceSpec | undefined>;
    /**
     * PingSourceStatus defines the observed state of PingSource (from the controller).
     */
    public readonly status!: pulumi.Output<outputs.sources.v1.PingSourceStatus | undefined>;

    /**
     * Create a PingSource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PingSourceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "sources.knative.dev/v1";
            resourceInputs["kind"] = "PingSource";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PingSource.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PingSource resource.
 */
export interface PingSourceArgs {
    apiVersion?: pulumi.Input<"sources.knative.dev/v1">;
    kind?: pulumi.Input<"PingSource">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * PingSourceSpec defines the desired state of the PingSource (from the client).
     */
    spec?: pulumi.Input<inputs.sources.v1.PingSourceSpecArgs>;
    /**
     * PingSourceStatus defines the observed state of PingSource (from the controller).
     */
    status?: pulumi.Input<inputs.sources.v1.PingSourceStatusArgs>;
}
