// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { PingSourceArgs } from "./pingSource";
export type PingSource = import("./pingSource").PingSource;
export const PingSource: typeof import("./pingSource").PingSource = null as any;
utilities.lazyLoad(exports, ["PingSource"], () => require("./pingSource"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:sources.knative.dev/v1beta2:PingSource":
                return new PingSource(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("knative-pulumi", "sources.knative.dev/v1beta2", _module)
