// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { IntegrationSourceArgs } from "./integrationSource";
export type IntegrationSource = import("./integrationSource").IntegrationSource;
export const IntegrationSource: typeof import("./integrationSource").IntegrationSource = null as any;
utilities.lazyLoad(exports, ["IntegrationSource"], () => require("./integrationSource"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:sources.knative.dev/v1alpha1:IntegrationSource":
                return new IntegrationSource(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("knative-pulumi", "sources.knative.dev/v1alpha1", _module)
