// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * IntegrationSource is an event source that starts a container image which generates events under certain situations and sends messages to a sink URI
 */
export class IntegrationSource extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationSource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): IntegrationSource {
        return new IntegrationSource(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:sources.knative.dev/v1alpha1:IntegrationSource';

    /**
     * Returns true if the given object is an instance of IntegrationSource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationSource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationSource.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"sources.knative.dev/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"IntegrationSource" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    public readonly spec!: pulumi.Output<outputs.sources.v1alpha1.IntegrationSourceSpec | undefined>;
    public readonly status!: pulumi.Output<outputs.sources.v1alpha1.IntegrationSourceStatus | undefined>;

    /**
     * Create a IntegrationSource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IntegrationSourceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "sources.knative.dev/v1alpha1";
            resourceInputs["kind"] = "IntegrationSource";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.sources.v1alpha1.integrationSourceSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntegrationSource.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a IntegrationSource resource.
 */
export interface IntegrationSourceArgs {
    apiVersion?: pulumi.Input<"sources.knative.dev/v1alpha1">;
    kind?: pulumi.Input<"IntegrationSource">;
    metadata?: pulumi.Input<ObjectMeta>;
    spec?: pulumi.Input<inputs.sources.v1alpha1.IntegrationSourceSpecArgs>;
    status?: pulumi.Input<inputs.sources.v1alpha1.IntegrationSourceStatusArgs>;
}
