// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { IntegrationSinkArgs } from "./integrationSink";
export type IntegrationSink = import("./integrationSink").IntegrationSink;
export const IntegrationSink: typeof import("./integrationSink").IntegrationSink = null as any;
utilities.lazyLoad(exports, ["IntegrationSink"], () => require("./integrationSink"));

export { JobSinkArgs } from "./jobSink";
export type JobSink = import("./jobSink").JobSink;
export const JobSink: typeof import("./jobSink").JobSink = null as any;
utilities.lazyLoad(exports, ["JobSink"], () => require("./jobSink"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:sinks.knative.dev/v1alpha1:IntegrationSink":
                return new IntegrationSink(name, <any>undefined, { urn })
            case "kubernetes:sinks.knative.dev/v1alpha1:JobSink":
                return new JobSink(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("knative-pulumi", "sinks.knative.dev/v1alpha1", _module)
