// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * IntegrationSink sends events to generic event sink
 */
export class IntegrationSink extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationSink resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): IntegrationSink {
        return new IntegrationSink(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:sinks.knative.dev/v1alpha1:IntegrationSink';

    /**
     * Returns true if the given object is an instance of IntegrationSink.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationSink {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationSink.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"sinks.knative.dev/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"IntegrationSink" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * Spec defines the desired state of the IntegrationSink.
     */
    public readonly spec!: pulumi.Output<outputs.sinks.v1alpha1.IntegrationSinkSpec | undefined>;
    /**
     * Status represents the current state of the IntegrationSink. This data may be out of date.
     */
    public readonly status!: pulumi.Output<outputs.sinks.v1alpha1.IntegrationSinkStatus | undefined>;

    /**
     * Create a IntegrationSink resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IntegrationSinkArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "sinks.knative.dev/v1alpha1";
            resourceInputs["kind"] = "IntegrationSink";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.sinks.v1alpha1.integrationSinkSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntegrationSink.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a IntegrationSink resource.
 */
export interface IntegrationSinkArgs {
    apiVersion?: pulumi.Input<"sinks.knative.dev/v1alpha1">;
    kind?: pulumi.Input<"IntegrationSink">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Spec defines the desired state of the IntegrationSink.
     */
    spec?: pulumi.Input<inputs.sinks.v1alpha1.IntegrationSinkSpecArgs>;
    /**
     * Status represents the current state of the IntegrationSink. This data may be out of date.
     */
    status?: pulumi.Input<inputs.sinks.v1alpha1.IntegrationSinkStatusArgs>;
}
