// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * JobSink triggers long-running jobs when an event occur.
 */
export class JobSink extends pulumi.CustomResource {
    /**
     * Get an existing JobSink resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): JobSink {
        return new JobSink(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:sinks.knative.dev/v1alpha1:JobSink';

    /**
     * Returns true if the given object is an instance of JobSink.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is JobSink {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === JobSink.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"sinks.knative.dev/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"JobSink" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * Spec defines the desired state of the JobSink.
     */
    public readonly spec!: pulumi.Output<outputs.sinks.v1alpha1.JobSinkSpec | undefined>;
    /**
     * Status represents the current state of the JobSink. This data may be out of date.
     */
    public readonly status!: pulumi.Output<outputs.sinks.v1alpha1.JobSinkStatus | undefined>;

    /**
     * Create a JobSink resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: JobSinkArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "sinks.knative.dev/v1alpha1";
            resourceInputs["kind"] = "JobSink";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(JobSink.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a JobSink resource.
 */
export interface JobSinkArgs {
    apiVersion?: pulumi.Input<"sinks.knative.dev/v1alpha1">;
    kind?: pulumi.Input<"JobSink">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Spec defines the desired state of the JobSink.
     */
    spec?: pulumi.Input<inputs.sinks.v1alpha1.JobSinkSpecArgs>;
    /**
     * Status represents the current state of the JobSink. This data may be out of date.
     */
    status?: pulumi.Input<inputs.sinks.v1alpha1.JobSinkStatusArgs>;
}
