// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { ParallelArgs } from "./parallel";
export type Parallel = import("./parallel").Parallel;
export const Parallel: typeof import("./parallel").Parallel = null as any;
utilities.lazyLoad(exports, ["Parallel"], () => require("./parallel"));

export { SequenceArgs } from "./sequence";
export type Sequence = import("./sequence").Sequence;
export const Sequence: typeof import("./sequence").Sequence = null as any;
utilities.lazyLoad(exports, ["Sequence"], () => require("./sequence"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:flows.knative.dev/v1:Parallel":
                return new Parallel(name, <any>undefined, { urn })
            case "kubernetes:flows.knative.dev/v1:Sequence":
                return new Sequence(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("knative-pulumi", "flows.knative.dev/v1", _module)
