// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * Sequence defines a sequence of Subscribers that will be wired in series through Channels and Subscriptions.
 */
export class Sequence extends pulumi.CustomResource {
    /**
     * Get an existing Sequence resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Sequence {
        return new Sequence(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:flows.knative.dev/v1:Sequence';

    /**
     * Returns true if the given object is an instance of Sequence.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Sequence {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Sequence.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"flows.knative.dev/v1" | undefined>;
    public readonly kind!: pulumi.Output<"Sequence" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * Spec defines the desired state of the Sequence.
     */
    public readonly spec!: pulumi.Output<outputs.flows.v1.SequenceSpec | undefined>;
    /**
     * Status represents the current state of the Sequence. This data may be out of date.
     */
    public readonly status!: pulumi.Output<outputs.flows.v1.SequenceStatus | undefined>;

    /**
     * Create a Sequence resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SequenceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "flows.knative.dev/v1";
            resourceInputs["kind"] = "Sequence";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Sequence.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Sequence resource.
 */
export interface SequenceArgs {
    apiVersion?: pulumi.Input<"flows.knative.dev/v1">;
    kind?: pulumi.Input<"Sequence">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Spec defines the desired state of the Sequence.
     */
    spec?: pulumi.Input<inputs.flows.v1.SequenceSpecArgs>;
    /**
     * Status represents the current state of the Sequence. This data may be out of date.
     */
    status?: pulumi.Input<inputs.flows.v1.SequenceStatusArgs>;
}
