// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { ImageArgs } from "./image";
export type Image = import("./image").Image;
export const Image: typeof import("./image").Image = null as any;
utilities.lazyLoad(exports, ["Image"], () => require("./image"));

export { ImageListArgs } from "./imageList";
export type ImageList = import("./imageList").ImageList;
export const ImageList: typeof import("./imageList").ImageList = null as any;
utilities.lazyLoad(exports, ["ImageList"], () => require("./imageList"));

export { ImagePatchArgs } from "./imagePatch";
export type ImagePatch = import("./imagePatch").ImagePatch;
export const ImagePatch: typeof import("./imagePatch").ImagePatch = null as any;
utilities.lazyLoad(exports, ["ImagePatch"], () => require("./imagePatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:caching.internal.knative.dev/v1alpha1:Image":
                return new Image(name, <any>undefined, { urn })
            case "kubernetes:caching.internal.knative.dev/v1alpha1:ImageList":
                return new ImageList(name, <any>undefined, { urn })
            case "kubernetes:caching.internal.knative.dev/v1alpha1:ImagePatch":
                return new ImagePatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("knative-pulumi", "caching.internal.knative.dev/v1alpha1", _module)
